name = "hono-api"
main = "src/index.ts"
compatibility_date = "2024-10-21"
compatibility_flags = [ "nodejs_compat" ]

 [vars]
 SUPABASE_URL = "https://tzhaoojsmpnhcvukkfgb.supabase.co"
 SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6aGFvb2pzbXBuaGN2dWtrZmdiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcyOTU1NzIyNCwiZXhwIjoyMDQ1MTMzMjI0fQ.UHgomn_tHDtN4UzyMhgDayHA7Og7Sm-KCgAR4FUbIWI"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1